#!/bin/sh -eu
# SPDX-License-Identifier: WTFPL

if [ -z "${FXRELAY_TOKEN-}" ]
then
	echo '$FXRELAY_TOKEN must be set' >&2
	exit 1
fi

curl --fail --show-error --silent \
	--max-time 60 \
	--header "Authorization: Token $FXRELAY_TOKEN" \
	https://relay.firefox.com/api/v1/relayaddresses/
