variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONDEVMODE: "1"

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"
    - "$CI_PROJECT_DIR/.cache/apt"

# TODO isolate venvs, don't install all locales
test-generic:
  stage: test
  image: python:3-slim
  before_script:
    - 'mkdir -p "$CI_PROJECT_DIR/.cache/apt/partial"'
    - "rm -f /etc/apt/apt.conf.d/docker-clean"
    - 'echo "Dir::Cache::Archives \"$CI_PROJECT_DIR/.cache/apt\";" >> /etc/apt/apt.conf'

  script: |
    set -eu
    apt update
    apt install -y --no-install-recommends locales-all # for sort-with-numbers
    apt install -y --no-install-recommends sqlite3 # for *sqlite*
    pip install pytest || exit 1

    err=1
    for f in "$CI_PROJECT_DIR"/*/test.py "$CI_PROJECT_DIR"/*/test.sh
    do
      echo "Testing $f" >&2
      cd "$(dirname "$f")"
      if [ -f requirements.txt ]
      then
        pip install -r requirements.txt
      fi >&2
      "$f" >&2 || echo "FAILED for $f"
    done | grep FAILED || err=0
    exit $err

lint-shellcheck:
  stage: test
  image: docker.io/pipelinecomponents/shellcheck
  script: |
    err=1
    set -eu
    grep -r -l '^# shellcheck enable=' "$CI_PROJECT_DIR"/* | while read file
    do
      shellcheck "$file"
    done | grep . || err=0
    exit $err

lint-python:
  stage: test
  image: python:3-slim
  script:
    - "pip install flake8"
    - "find -name '*.py' -exec flake8 --select E999 '{}' +"
    - "flake8 --select E999 $(git grep -r '#!/usr/bin/env python3' -l)"
