#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

import argparse
import urllib.parse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.set_defaults(func=urllib.parse.unquote)
    parser.add_argument(
        '-p', '--plus', dest='func', action='store_const',
        const=urllib.parse.unquote_plus,
    )
    parser.add_argument('url')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    print(args.func(args.url))
