#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

# reads a password on TTY (not stdin) and show it on stdout

import argparse
import getpass


parser = argparse.ArgumentParser()
parser.add_argument("prompt", default="Password:", nargs="?")
args = parser.parse_args()

prompt = f"{args.prompt.rstrip()} "

print(getpass.getpass(prompt))
