#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

# reads a password on TTY (not stdin) and show it on stdout

import getpass
import sys


try:
    prompt = f"{sys.argv[1].rstrip()} "
except IndexError:
    prompt = "Password: "

print(getpass.getpass(prompt))
