#!/bin/sh -e
# SPDX-License-Identifier: WTFPL
# shellcheck enable=
# usage: show-args ARGUMENTS...
# just show args, one per line
# example:
#   show-args foo "bar baz"
#     foo
#     bar baz

printf "%s\\n" "$@"
