#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

import argparse
import csv
import locale
import signal
import sys


if __name__ == "__main__":
	locale.setlocale(locale.LC_ALL, '')

	signal.signal(signal.SIGINT, signal.SIG_DFL)
	signal.signal(signal.SIGPIPE, signal.SIG_DFL)

	parser = argparse.ArgumentParser(
		description="Output one CSV row with arguments as cells",
	)
	parser.add_argument('-s', '--separator', default=',')
	parser.add_argument('args', nargs='*')
	args = parser.parse_args()

	writer = csv.writer(sys.stdout, delimiter=args.separator)
	writer.writerow(args.args)
