#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

import argparse
import configparser
import json
import sys


def main():
	argparser = argparse.ArgumentParser()
	argparser.add_argument("file", nargs="?", default="-")
	args = argparser.parse_args()

	if args.file == "-":
		fp = sys.stdin
	else:
		fp = open(args.file)

	cfg = configparser.ConfigParser()
	with fp:
		cfg.read_file(fp)
	d = {
		section: {
			k: v
			for k, v in cfg[section].items()
		}
		for section in cfg
	}
	print(json.dumps(d, indent=4))


if __name__ == "__main__":
	main()
