#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL
# original: 2007
# rewritten for modernization in 2019

from argparse import ArgumentParser, FileType
import os
import signal
import sys

def has_colors():
    if os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("CLICOLOR_FORCE") or os.environ.get("FORCE_COLOR"):
        return True
    return sys.stdout.isatty()

try:
    import termcolor
except ImportError:
    def styled(s, *args, **kwargs):
        return s
else:
    def styled(s, *args, **kwargs):
        if has_colors():
            s = termcolor.colored(s, *args, **kwargs)
        return s


REPLACES = {
    '\n': styled(r'\n', 'green'),
    '\t': styled(r'\t', 'green'),
    '\r': styled(r'\r', 'green'),
    '\f': styled(r'\f', 'green'),
    '\b': styled(r'\b', 'green'),
    '\a': styled(r'\a', 'green'),
    '\v': styled(r'\v', 'green'),
    '\x00': styled(r'\0', attrs=['reverse']),
    ' ': styled('sp', 'green'),
}

def transform(b):
    char = chr(b)

    if char in REPLACES:
        return f'{REPLACES[char]}'
    elif 0x20 < b < 0x7f:
        return f'{char} '
    else:
        return f"{styled(f'{b:02X}', attrs=['reverse'])}"


def print_line(line):
    print(' '.join(transform(b) for b in line))


def main():
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

    parser = ArgumentParser(description='Visual Hex Dump')
    parser.add_argument(
        "-L", "--line-numbers", action="store_true",
        help="Display line numbers (in decimal base, starting at 1)",
    )
    parser.add_argument(
        "--line-addresses", action="store_true",
        help="Display byte offsets at start of lines (in hexadecimal base)",
    )
    parser.add_argument('--hex', action='store_true')
    parser.add_argument('file', nargs='?', type=FileType('rb'), default=sys.stdin.buffer)
    args = parser.parse_args()

    total = 0
    lineno = 1
    while True:
        line = args.file.readline()
        if not line:
            break

        if args.line_addresses:
            print(f'{total:08x} ', end='')
        elif args.line_numbers:
            print(f"{lineno:08} ", end="")

        if args.hex:
            print(' '.join(f'{b:02x}' for b in line))
        else:
            print_line(line)

        total += len(line)
        lineno += 1


if __name__ == '__main__':
    main()
