#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL
# basic GIF viewer using Qt libs
# usage: qgifview FILE.GIF

import sys

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QMovie
from PyQt5.QtWidgets import QApplication, QLabel


app = QApplication(sys.argv)

args = app.arguments()
if len(args) != 2 or sys.argv[1] in {'-h', '--help'}:
    print('usage: %s FILE.GIF' % args[0], file=sys.stderr)
    sys.exit(1)

movie = QMovie(args[1])
if not movie.isValid():
    print('invalid GIF file: %s' % args[1], file=sys.stderr)
    sys.exit(2)


class MyLabel(QLabel):
    def keyPressEvent(self, ev):
        if ev.key() == Qt.Key_Escape:
            self.close()


label = MyLabel()
label.setMovie(movie)

movie.start() # start first so label gets right default size
label.show()

movie.finished.connect(movie.start) # loop

sys.exit(app.exec_())
