#!/bin/sh -e
# SPDX-License-Identifier: WTFPL
# shellcheck enable=
# list pass(1) entries in find(1) format, not tree(1) format
# example:
#
#    foo/bar
#    foo/baz
#
# instead of:
#
#    foo
#    |-- bar
#    |-- baz


cd "${PASSWORD_STORE_DIR:-$HOME/.password-store}"
find . -name "*.gpg" | sed -e 's:^\./::' -e 's:\.gpg$::'
