#!/usr/bin/env python
# license: Do What The Fuck You Want To Public License version 2 [http://www.wtfpl.net/]

import sys, os
import itertools

blocks = iter(lambda: sys.stdin.read(4096), '')
chars = itertools.chain.from_iterable(blocks)
digits = itertools.ifilterfalse(str.isspace, chars)
pairs = itertools.izip_longest(digits, digits) # longest to catch EOF

try:
	for pair in pairs:
		sys.stdout.write(chr(int(pair[0] + pair[1], 16)))
except (IOError, KeyboardInterrupt):
	sys.exit(os.EX_IOERR)
except ValueError:
	sys.stderr.write('Unexpected data: %s\n' % ''.join(pair))
	sys.exit(os.EX_DATAERR)
except TypeError:
	sys.stderr.write('Unexpected EOF after: %s\n' % pair[0])
	sys.exit(os.EX_DATAERR)
