#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

# - takes a malformed ASCII-drawn table as stdin or file, for example:
#    +-----+-----+
#    | foo | bar |
#    +-----+-----+
#    | a long cell | short |
#    | x | longer cell ? |
#    +--+--+
#
# - outputs a well-formed table:
#    +-------------+---------------+
#    |     foo     |      bar      |
#    +-------------+---------------+
#    | a long cell |     short     |
#    |      x      | longer cell ? |
#    +-------------+---------------+

# /// script
# dependencies = ["prettytable"]
# ///

from argparse import ArgumentParser
from fileinput import input
import re
import sys

from prettytable import PrettyTable, HEADER


replacements = {
    '─=': '-',
    '│': '|',
    '┘┐└┌├┬┼┴┤': '+',
}
box_chars = ''.join(replacements.keys()) + ''.join(replacements.values())
box_chars_regex = re.compile(r'[%s\s]+' % re.escape(box_chars))


table_regex = re.compile(
    r"""
    ^
    \s*(
        [-─=]+
        | [+|│┌└├] [+-┬┼┴─\s]* [+|│┤┘┐]
        | [|│] .* [|│]
    )\s*
    $
    """,
    re.X
)


def dump_table(rows, table_conf=None):
    if not rows:
        return

    table = PrettyTable()
    if table_conf:
        table_conf(table)
    table.align = args.align

    header, rows = rows[0], rows[1:]

    assert not header[0]
    assert not header[-1]
    table.field_names = header[1:-1]
    for row in rows:
        assert not row[0]
        assert not row[-1]
        table.add_row(row[1:-1])
    print(table)


conf = None

arger = ArgumentParser()
arger.add_argument(
    "--markdown", action="store_true",
    help="Output table in markdown format",
)
arger.add_argument(
    "--align", default="c",
    metavar="CHARACTER",
    help="Where to align text in cells. CHARACTER can be 'l' for left, 'c' for\n"
    + "center or 'r' for right",
)
arger.add_argument(
    "file", nargs="*",
    help="File on which to read misaligned tables (or stdin if not given)",
)
args = arger.parse_args()

if args.markdown:
    def conf(table):
        table.hrules = HEADER
        table.junction_char = "|"


rows = []
for line in input(args.file):
    if not table_regex.fullmatch(line):
        dump_table(rows, conf)
        rows = []
        print(line, end='')
        continue

    if box_chars_regex.fullmatch(line):
        continue

    line = line.rstrip()

    row = [el.strip() for el in re.split('[│|]', line)]
    rows.append(row)
dump_table(rows, conf)
