#!/usr/bin/env python
# based on Fisher-Yates shuffle
# license: WTFPL

import random, sys

for n, line in enumerate(sys.stdin):
	if not random.randrange(n + 1):
		choice = line
sys.stdout.write(choice)
