#!/usr/bin/env python3
# based on Fisher-Yates shuffle
# SPDX-License-Identifier: WTFPL

import fileinput
import random
import sys

choice = None
for n, line in enumerate(fileinput.input()):
	if not random.randrange(n + 1):
		choice = line

if choice is not None:
	sys.stdout.write(choice)
