#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

import re
import sys


pattern = re.compile(sys.argv[1])

groups = {}

while True:
    try:
        line = input()
    except EOFError:
        break

    match = pattern.search(line)
    if match:
        if pattern.groups:
            k = "".join(match.groups())
        else:
            k = match[0]
    else:
        k = None
    groups.setdefault(k, []).append(line)


for k in sorted(groups, key=lambda k: k or ""):
    lines = groups[k]
    print(f"{k}:")
    for line in lines:
        print(line)
