#!/usr/bin/python3
# license: Do What The Fuck You Want To Public License version 2 [http://www.wtfpl.net/]

# sort stdin like sort(1) but consider digit characters as numbers to sort them.
# e.g. sort(1) could output this:
# - foo1.bar
# - foo10.bar
# - foo2.bar
# and sort-with-numbers would output:
# - foo1.bar
# - foo2.bar
# - foo10.bar
# sort-with-numbers can perform "version sorting" naturally

import fileinput
import re


def extract_ints(line):
    # split the string into parts:
    # - string with digits are coerced to int and thus compared as ints
    # - non-digits are compared as string

    # since we then rely in python's standard comparison operators
    # a str cannot be compared to an int...
    # so we prepend a type id that makes only compatible types are compared
    # `(type_id, real_value)`
    # - 0 if int
    # - 1 if str
    # when 2 type_id are different, python will sort them apart
    # without considering the real_value to compare

    ret = []
    for part_str in re.findall(r"\D+|\d+", line):
        try:
            part_as_num = int(part_str)
        except ValueError:
            # not a number, keep as is
            ret.append((1, part_str))
        else:
            ret.append((0, part_as_num))

    return tuple(ret)


all_lines = list(fileinput.input())
all_lines.sort(key=extract_ints)
# warning: fileinput keeps all newlines
print("".join(all_lines), end="")
