#!/usr/bin/env python3
# SPDX-License-Identifier: WTFPL

import argparse
import json
import tomllib
import sys


def main():
	argparser = argparse.ArgumentParser()
	argparser.add_argument("file", nargs="?", default="-")
	args = argparser.parse_args()

	if args.file == "-":
		fp = sys.stdin.buffer
	else:
		fp = open(args.file, "rb")

	with fp:
		d = tomllib.load(fp)
	print(json.dumps(d, indent=4, default=str))


if __name__ == "__main__":
	main()
